dbt_production_blueprint_duckdb:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: dev.duckdb
      schema: main
      threads: 4

    ci:
      type: duckdb
      path: ci.duckdb
      schema: main
      threads: 4

    # Snowflake profile (for production use)
    snowflake:
      type: snowflake
      account: <your_account_identifier>
      user: <your_username>
      password: <your_password>
      role: <your_role>
      database: <your_database>
      warehouse: <your_warehouse>
      schema: dbt_dev
      threads: 4
      query_tag: dbt_production_blueprint

dbt_production_blueprint_postgres:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5433
      user: dbt_user
      password: dbt_password
      database: dbt_production_blueprint
      schema: dbt_dev
      threads: 4
